(function () {
  const {esc, usd, cite, diffBlock} = SO;
  const el = document.getElementById('stage'), status = document.getElementById('status');
  let data, pending = null, busy = false, last = '';
  const money = n => usd(Number(n));
  const action = r => !r ? 'Consumed by the matching receipt' : r.action === 'match_adjust' ? `Match; book ${(r.adjustments || []).map(a=>`${money(a.amount)} to ${a.account}`).join(', ')}` : r.action === 'book' ? `Book ${(r.adjustments || []).map(a=>`${money(Math.abs(a.amount))} to ${a.account}`).join(', ')}` : r.action === 'escalate' ? `Review${r.escalate_to ? ' with '+r.escalate_to.replaceAll('_',' ') : ''}` : r.action.replaceAll('_',' ');
  function evidence(c, cases) {
    return `<details class="demo-details"><summary>Open the historical evidence (${cases.length} examples)</summary>${cases.map(p=>`<div class="demo-evidence">${cite(c.client,p.id)} · ${esc(p.date)} · ${money(p.amount)}<p>${esc(p.text || '')}</p>${p.booked.length ? p.booked.map(b=>`${money(b.amount)} → ${esc(b.account)} · posted by ${esc(b.by)}`).join('<br>') : 'No adjustment recorded'}${p.senior_involved ? '<p>A senior participated in this decision.</p>' : ''}</div>`).join('')}</details>`;
  }
  function decision(c) {
    const i = c.items.find(i=>i.item_id.endsWith('STAGE-SHORT-0'));
    if (!i) return '';
    const pendingGroup=c.groups.find(g=>g.approve_rule && g.items.includes(i.item_id));
    const r=pendingGroup?.rule || i.rule;
    const original=pendingGroup?.rule || i.original_rule || r;
    return `<article class="panel demo-card"><div class="label">${esc(c.name)} · version ${c.version}</div><h3>${esc(action(i.resolution))}</h3>${pendingGroup ? '<p class="demo-note">History suggests the rule below, but the account choice needs sign-off. Adopt it in section 03 to resolve this receipt and its siblings.</p>' : ''}${r ? `<div class="demo-rule">${esc(r.text)}<p class="demo-note">${esc(r.id)} · ${esc(r.status)} · Original inference: ${original.backtest?.support || 0} historical agreements / ${original.backtest?.conflicts || 0} disagreements${r.valid_from ? ' · Signed policy effective '+esc(r.valid_from) : ''}</p></div>` : `<p>${esc(i.resolution.rationale)}</p>`}${i.resolution.reason === 'no_rule' ? '<p class="demo-note">No compiled rule resolves this case. This is a review outcome, not proof of a learned escalation policy.</p>' : ''}${evidence(c,pendingGroup?.precedents || i.precedents)}<details class="demo-details"><summary>Execution trace</summary>${i.trace.map(t=>`<p class="demo-note">${esc(t.label)}: ${esc(typeof t.output === 'string' ? t.output : JSON.stringify(t.output))}</p>`).join('')}${!i.trace.length ? `<p class="demo-note">${esc(i.resolution.rationale)}</p>` : ''}</details></article>`;
  }
  function group(c,g,n) {
    return `<article class="panel demo-card"><div class="label">${esc(c.name)} · one policy question</div><h3>${g.affected} cases can clear with one answer</h3><div class="demo-rule">${esc(g.rule_text)}</div><p class="demo-note">The routine examples reach ${money(g.lo)}${g.hi == null ? '; no upper boundary is established.' : '; the next different outcome is at '+money(g.hi)+'.'} Set the boundary you authorize, then inspect the affected cases.</p>${g.approve_rule ? `<details class="demo-details"><summary>Why this rule needs explicit sign-off</summary><p class="demo-note">${esc(g.rule.open_question || 'This rule is still proposed.')}</p></details>` : ''}${evidence(c,g.precedents)}<form class="demo-form" data-group="${c.client}:${n}"><label>Your approved limit<input aria-label="Approved limit for ${esc(c.name)} ${esc(g.rule_id)}" type="number" step="0.01" value="${g.value}" required></label>${g.approve_rule ? `<label style="max-width:360px;display:flex;align-items:center"><input type="checkbox" required style="width:auto">Adopt this rule and account with this limit from ${data.period}-01. Earlier decisions stay historical.</label>` : ''}<button class="demo-button" type="submit">Preview ${g.affected} cases</button></form><p class="demo-note">The starting amount is an editable rehearsal input, not an inferred limit. Answering as ${esc(c.role?.replaceAll('_',' ') || 'a senior')}. This changes policy for matching cases, not just the item on screen.</p></article>`;
  }
  function render() {
    el.innerHTML = `<div class="demo-banner">${esc(data.disclosure)}</div>
      <section class="demo-section" id="history"><div class="demo-heading"><h2>01 / The policy comes from the trail.</h2><span class="label">Saved model induction · no model wait on stage</span></div><div class="demo-grid">${data.results.map(c=>`<article class="panel demo-card"><div class="label">${esc(c.name)}</div><div class="demo-stats"><div><div class="demo-stat">${c.history_bank_lines}</div><div class="label">historical bank lines</div></div><div><div class="demo-stat">${c.rules.length}</div><div class="label">inferred rules</div></div></div><p>${esc(c.origin.training_window)}. Model reads reconciliation links, adjustment journals, approvals and emails. Code replays the proposed rules against those decisions.</p><details class="demo-details"><summary>Inspect induction provenance and rules</summary><p class="demo-note">Source: ${esc(c.origin.track)} v${c.origin.version}<br>Policy file SHA-256: <span style="overflow-wrap:anywhere">${esc(c.origin.sha256)}</span></p>${c.rules.map(r=>`<div class="demo-evidence">${esc(r.id)} · ${esc(r.status)}<p>${esc(r.text)}</p>${r.backtest?.support || 0} agreements, ${r.backtest?.conflicts || 0} disagreements</div>`).join('')}</details></article>`).join('')}</div><div class="demo-flow"><span>ERP history</span><span>→ Model proposes rules</span><span>→ Code checks precedents</span><span>→ Human resolves uncertainty</span><span>→ Rules execute without tokens</span></div></section>
      <section class="demo-section" id="decision"><div class="demo-heading"><h2>02 / What do you do about $12.40?</h2><span class="label">Same $4,800 invoice · same $4,787.60 receipt</span></div><div class="demo-grid">${data.results.map(decision).join('')}</div></section>
      <section class="demo-section" id="teach"><div class="demo-heading"><h2>03 / Answer once. Clear the group.</h2><span class="label">Live code · $0 model cost</span></div>${last ? `<div class="demo-banner" role="status">${last}</div>` : ''}<div class="demo-grid">${data.results.map(c=>`<article class="panel demo-card"><div class="label">${esc(c.name)} · demonstration bank items only</div><div class="demo-stats"><div><div class="demo-stat">${c.baseline.needs_review} → ${c.summary.needs_review}</div><div class="label">items needing review</div></div><div><div class="demo-stat">${c.summary.automatic_bank_items}/${c.summary.bank_items}</div><div class="label">cleared by code</div></div></div>${c.undoable.map(e=>`<button class="demo-button secondary" data-undo="${c.client}:${esc(e.correction_id)}">Undo latest answer</button>`).join('')}</article>`).join('')}</div><div id="preview-slot"></div><div class="demo-grid" style="margin-top:18px">${data.results.flatMap(c=>c.groups.map((g,n)=>group(c,g,n))).join('') || '<p>No numeric answer currently clears additional cases. Review the remaining evidence or use Undo to rehearse again.</p>'}</div><details class="demo-details"><summary>See every remaining review item</summary>${data.results.map(c=>`<h3>${esc(c.name)}</h3><table class="demo-table"><tbody>${c.items.filter(i=>i.item_kind==='bank'&&i.resolution.action==='escalate').map(i=>`<tr><td>${cite(c.client,i.item_id)}</td><td>${money(i.record.amount)}</td><td>${esc(i.control_flags?.length ? 'Verification required' : i.resolution.reason || 'Policy requires review')}</td></tr>`).join('')}</tbody></table>`).join('')}</details></section>
      <section class="demo-section" id="control"><div class="demo-heading"><h2>04 / An exact match can still be unsafe.</h2><span class="label">Approval does not bypass verification</span></div><div class="panel demo-card demo-control"><div><div class="demo-held">Bank details changed.<br>Both payments stay held.</div><p class="demo-note">The amounts and references match. A prior email asks for new bank details. The deterministic control prevents automatic reconciliation until the change is verified.</p></div><div>${data.results.map(c=>{const held=c.items.filter(i=>i.item_kind==='bank'&&i.control_flags?.length);return `<h3>${esc(c.name)}: ${held.length} held</h3>${held.map(i=>`<p>${cite(c.client,i.item_id)} · ${money(Math.abs(i.record.amount))}<br><span class="demo-note">${esc(i.control_flags.map(f=>f.detail||f.flag).join('; '))}</span><br>${[...new Set(i.control_flags.flatMap(f=>f.evidence_ids||[]))].map(id=>cite(c.client,id)).join(' ')}</p>`).join('')}`}).join('')}</div></div></section>
      <footer class="demo-footer">Measured here: review workload and decisions changed on these constructed cases. These counts are not accuracy, dollars saved, or a blind-test result. The product reconciles records; it does not initiate payments.</footer>`;
    el.querySelectorAll('form[data-group]').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const [client,n]=f.dataset.group.split(':');const c=data.results.find(c=>c.client===client),g=c.groups[Number(n)];await act(async()=>{const p=await post(g.approve_rule ? '/api/playbook/preview-policy' : '/api/playbook/preview-band',{confirm_rule:g.approve_rule,effective_from:g.approve_rule ? data.period+'-01' : null,client,track:data.track,period:data.period,rule_id:g.rule_id,condition:g.condition,role:c.role,answer:'limit',limit:Number(f.querySelector('input').value)});if(p.held)throw Error(p.held);pending={...p,client,role:c.role};renderPreview();});}));
    el.querySelectorAll('[data-undo]').forEach(b=>b.addEventListener('click',async()=>{if(busy)return;if(!b.dataset.confirm){b.dataset.confirm='yes';b.textContent='Confirm undo';return;}const [client,correction_id]=b.dataset.undo.split(':');const c=data.results.find(c=>c.client===client);await act(async()=>{const r=await post('/api/retract',{client,track:data.track,role:c.role,correction_id,note:'Judging demonstration: undo latest policy answer'});last=`Answer undone. ${r.resolutions_checked} prior items checked; ${r.reopened.length} reopened.`;pending=null;await load();document.getElementById('teach').scrollIntoView();});}));
  }
  function renderPreview(){const p=pending;document.getElementById('preview-slot').innerHTML=`<section class="demo-preview"><div class="label">Not saved · inspect the change</div><h3>${p.before.needs_review} → ${p.after.needs_review} bank items need review</h3>${diffBlock(p.diff,{client:p.client})}<table class="demo-table"><thead><tr><th>Item</th><th>Before</th><th>After</th></tr></thead><tbody>${p.changed_items.map(i=>`<tr><td>${cite(p.client,i.item_id)}</td><td>${esc(action(i.before))}</td><td>${esc(action(i.after))}</td></tr>`).join('')}</tbody></table><div class="demo-form"><button id="commit" class="demo-button">Approve and rerun</button><button id="cancel" class="demo-button secondary">Cancel</button></div><p class="demo-note">The server checks the policy and evidence again before applying. A stale preview cannot be approved.</p></section>`;document.getElementById('preview-slot').scrollIntoView();document.getElementById('cancel').onclick=()=>{pending=null;document.getElementById('preview-slot').innerHTML='';};document.getElementById('commit').onclick=()=>act(async()=>{const r=await post('/api/playbook/apply-preview',{preview_id:p.preview_id,role:p.role});if(!r.diff)throw Error(r.held||'No policy change was saved');last=`One answer applied. ${r.reran.length} previously reviewed cases now clear without model calls. Policy version ${r.new_version}.`;pending=null;await load();document.getElementById('teach').scrollIntoView();});}
  async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(typeof v.detail==='string'?v.detail:JSON.stringify(v.detail));return v;}
  async function act(fn){if(busy)return;busy=true;status.textContent='Checking the policy and replaying cases…';el.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();status.textContent='';}catch(e){status.textContent=e.message;}finally{busy=false;el.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  async function load(){const r=await fetch('/api/stage');const v=await r.json();if(!r.ok)throw Error(v.detail||'Unable to load the judging sandbox');data=v;render();}
  load().then(()=>{status.textContent='';}).catch(e=>{status.textContent=e.message;});
})();
