(async function () {
  if (SO.track !== 'stage') return;
  const {esc,usd,cite,diffBlock}=SO;
  const main=document.querySelector('main');
  main.classList.add('inbox-main');
  let data,clientId='',selected='',filter=SO.presenting?'policy':'all',search='',preview=null,busy=false,message='',setup=false;
  const choices={};
  const label=r=>(r||'Reviewer').replaceAll('_',' ').replace(/^./,x=>x.toUpperCase()).replace(/\b(ar|ap)\b/gi,x=>x.toUpperCase());
  const c=()=>data.results.find(x=>x.client===clientId)||data.results[0];
  const role=()=>choices[c().client]||c().role;
  const bank=()=>c().items.filter(i=>i.item_kind==='bank');
  const isClear=i=>['match','match_adjust','book'].includes(i.resolution.action);
  function groups(){
    const list=[],claimed=new Set();
    const holds=bank().filter(i=>i.control_flags?.length);
    for(const item of holds){const key=item.record.counterparty||'Payment verification';let g=list.find(g=>g.id==='hold:'+key);if(!g){g={id:'hold:'+key,kind:'hold',title:'Verify payment details',subtitle:key,items:[]};list.push(g);}g.items.push(item);claimed.add(item.item_id);}
    for(const g of c().groups){const items=bank().filter(i=>g.items.includes(i.item_id));items.forEach(i=>claimed.add(i.item_id));list.push({id:g.question_id,kind:'policy',title:g.approve_rule?(g.rule.then.action==='match_adjust'?'Confirm how to handle shortfalls':'Confirm the suggested policy'):'Set the review limit',subtitle:g.rule.then.account ? 'Account '+g.rule.then.account+' · '+(c().chart[g.rule.then.account]||'') : g.rule_text,items,policy:g});}
    for(const i of bank().filter(i=>!claimed.has(i.item_id)&&!isClear(i))){list.push({id:i.item_id,kind:'review',title:i.record.description||'Review transaction',subtitle:'Needs '+label(i.resolution.escalate_to).toLowerCase(),items:[i]});}
    for(const i of bank().filter(isClear)){list.push({id:i.item_id,kind:'clear',title:i.record.description||'Resolved transaction',subtitle:'Resolved under '+(i.resolution.rule_id||'an exact match'),items:[i]});}
    return list;
  }
  const kindName={hold:'Verification required',policy:'One answer for the group',review:'Needs a decision',clear:'Resolved'};
  function evidence(g){const ps=g.policy?.precedents||g.items[0]?.precedents||[];return `<details><summary>Why Audita suggested this · ${ps.length} historical examples</summary>${ps.length?ps.map(p=>`<div class="inbox-evidence">${cite(c().client,p.id)} · ${esc(p.date)}<p>${esc(p.text||'')}</p>${p.booked.map(b=>`${usd(b.amount)} booked to ${esc(b.account)} by ${esc(b.by)}`).join('<br>')}</div>`).join(''):'No supporting examples are attached. Keep this in review until the missing information is resolved.'}</details>`;}
  function itemsTable(items){return `<table class="inbox-table"><thead><tr><th>Transaction</th><th>Amount</th><th>Difference</th><th>Date</th></tr></thead><tbody>${items.map(i=>`<tr><td>${cite(c().client,i.item_id).replace('>'+esc(i.item_id)+'</a>', '>'+esc(i.record.counterparty||i.record.description||i.item_id)+'</a>')}<div class="inbox-note">${esc(i.record.description||'')}</div></td><td>${usd(i.record.amount)}</td><td>${i.reference_invoice?.direction==='AR'&&i.record.amount>0?usd(i.reference_invoice.amount-i.record.amount):'N/A'}</td><td>${esc(i.record.date)}</td></tr>`).join('')}</tbody></table>`;}
  function detail(g){if(!g)return '<div class="panel inbox-empty">No items match this view. Try another filter or search.</div>';
    let action='';
    if(g.kind==='policy'){const p=g.policy;action=`<h3>The suggested policy</h3><p>${esc(p.rule_text)}</p>${p.rule.open_question?`<div class="inbox-callout"><strong>One thing to confirm</strong><br>${esc(p.rule.open_question)}</div>`:''}<form id="policy-form"><div class="inbox-actions"><label>Limit you authorize<input type="number" id="limit" step="0.01" required value="${p.value}"></label><label>Account<input aria-label="Adjustment account" value="${esc(p.rule.then.account||'')} ${esc(c().chart[p.rule.then.account]||'')}" disabled style="padding:12px;max-width:300px"></label></div>${p.approve_rule?`<label class="inbox-confirm"><input type="checkbox" required>I approve this rule and account with this limit, effective ${esc(data.period)}-01. Earlier decisions remain in the history.</label>`:''}<button class="inbox-btn" type="submit">Preview what changes</button><p class="inbox-note">Nothing changes until you review and approve the preview. The starting limit is an editable demo value.</p></form>${evidence(g)}`;}
    else if(g.kind==='hold'){const ids=[...new Set(g.items.flatMap(i=>i.control_flags.flatMap(f=>f.evidence_ids||[])))];action=`<div class="inbox-callout"><strong>The amount matches, but the bank details changed.</strong><br>${g.items.length} payments remain blocked from automatic reconciliation until the change is independently verified.</div><h3>What to do next</h3><ol><li>Contact the vendor using a previously known phone number.</li><li>Have an authorized reviewer record the verification against the source document.</li><li>Rerun reconciliation after that evidence is present.</li></ol><p>${ids.map(id=>cite(c().client,id)).join(' ')}</p><p class="inbox-note">Open the source email above. Verification must be recorded against that document before reconciliation can resume.</p>`;}
    else if(g.kind==='clear'){const r=g.items[0].resolution;action=`<div class="inbox-callout"><strong>No action needed.</strong><br>${esc(r.rationale||'Cleared by the matching rules.')}</div>${(r.adjustments||[]).map(a=>`<p>${usd(a.amount)} → ${esc(a.account)} ${esc(c().chart[a.account]||'')}</p>`).join('')}${evidence(g)}`;}
    else {const i=g.items[0];action=`<div class="inbox-callout"><strong>${esc(label(i.resolution.escalate_to))} needs to review this.</strong><br>${esc(i.rule?.open_question||i.rule?.text||i.resolution.rationale)}</div>${evidence(g)}<a class="inbox-btn secondary" href="playbook.html?client=${encodeURIComponent(c().client)}&track=stage&period=${data.period}">Open company policies</a><p class="inbox-note">This item needs context beyond a numeric approval. It stays in the queue.</p>`;}
    return `<section class="panel inbox-detail"><div class="inbox-kicker">${kindName[g.kind]} · ${g.items.length} transaction${g.items.length===1?'':'s'}</div><h2>${esc(g.title)}</h2>${g.kind==='policy'?`<p class="inbox-note">One company policy can resolve these ${g.items.length} related cases. You do not need to approve each transaction separately.</p>`:''}${SO.jev.panel(c(),g)}${action}<div id="inbox-preview"></div><h3>${g.items.length>1?'Related transactions':'Transaction'}</h3>${itemsTable(g.items)}<details><summary>Technical evidence and decision trace</summary>${g.items.map(i=>`<p><b>${esc(i.item_id)}</b><br>${esc(i.resolution.rationale||'')}</p>${i.trace.map(t=>`<p class="inbox-note">${esc(t.label)}: ${esc(typeof t.output==='string'?t.output:JSON.stringify(t.output))}</p>`).join('')}`).join('')}</details></section>`;
  }
  function setupPanel(){return `<section class="panel inbox-setup"><h2>Your workspace is ready to review</h2><p>For the hackathon, the sample companies are already loaded. Here is the setup a finance team would review before starting.</p><div class="inbox-steps"><div><div class="inbox-kicker">1 · Check the source</div><h3>${esc(c().name)}</h3><p>${c().history_bank_lines} historical bank transactions, with ledger links, adjustments and approvals.</p><p class="inbox-note">Synthetic sample data. No accounting system is connected and no upload is required for this demo.</p></div><div><div class="inbox-kicker">2 · Review learned policies</div><h3>${c().rules.length} suggested rules</h3><p>Learned from January and February. Uncertain rules still need your approval.</p><a href="playbook.html?client=${c().client}&track=stage&period=${data.period}">Inspect company policies ↗</a></div><div><div class="inbox-kicker">3 · Choose the reviewer</div><h3>${esc(label(role()))}</h3><p>Use the reviewer selector above to choose who is approving changes in this rehearsal.</p><p class="inbox-note">This is a demo role selector, not account authentication.</p></div></div><button class="inbox-btn" id="finish-setup">Start reviewing</button></section>`;}
  function render(){
    const all=groups();let visible=all.filter(g=>(filter==='all'?g.kind!=='clear':filter==='clear'?g.kind==='clear':g.kind===filter)&&(!search||[g.title,g.subtitle,...g.items.flatMap(i=>[i.item_id,i.record.description,i.record.counterparty])].join(' ').toLowerCase().includes(search.toLowerCase())));
    if(!visible.some(g=>g.id===selected))selected=(SO.presenting ? visible.find(g=>g.policy?.approve_rule) : null)?.id||visible[0]?.id||'';
    const g=visible.find(g=>g.id===selected),resolved=bank().filter(isClear).length,held=bank().filter(i=>i.control_flags?.length).length;
    main.innerHTML=`<div class="lede inbox-lede"><div class="label">Review workspace</div><h1>Your review queue</h1><p>Learn from past decisions. Answer one policy question. Clear the related cases.</p></div>${SO.presenting?`<section class="demo-cue"><b>One policy answer. Three receipts cleared.</b> Review the evidence, set a $15 limit, preview and approve. <a href="presenter.html" target="_blank">Demo script ↗</a></section>`:''}<div class="inbox-toolbar"><label>Company<select id="company">${data.results.map(x=>`<option value="${x.client}" ${x.client===c().client?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Reviewing as<select id="reviewer">${(c().roles||[c().role]).map(r=>`<option value="${esc(r)}" ${r===role()?'selected':''}>${esc(label(r))}</option>`).join('')}</select></label><span class="inbox-note">Sample company data · May 2026</span><button class="inbox-btn secondary" id="refresh">Refresh queue</button><button class="inbox-btn secondary" id="setup">${setup?'Close setup':'Workspace setup'}</button></div>${setup?setupPanel():''}${SO.presenting?'':SO.jev.connection()}<div class="inbox-status" role="status" aria-live="polite">${esc(message)}</div><div class="panel inbox-summary"><div class="inbox-counts"><div><strong>${bank().length-resolved}</strong><span>Transactions to review</span></div><div><strong>${c().groups.length}</strong><span>Policy questions</span></div><div><strong>${held}</strong><span>Need verification</span></div><div><strong>${resolved}</strong><span>Resolved</span></div></div>${c().undoable.length?`<div class="inbox-actions"><button class="inbox-btn secondary" id="undo">Undo latest policy answer</button><a href="playbook.html?client=${c().client}&track=stage&period=${data.period}">All changes and Undo history ↗</a></div>`:''}</div><div class="inbox-tabs" role="group" aria-label="Filter review queue">${[['all','To review'],['hold','Verification'],['policy','Policy questions'],['clear','Resolved']].map(([v,l])=>`<button data-filter="${v}" aria-pressed="${filter===v}">${l}</button>`).join('')}</div><div class="inbox-layout"><aside><input class="inbox-search" id="search" placeholder="Search transactions…" aria-label="Search review queue" value="${esc(search)}"><div class="inbox-list" style="margin-top:12px">${visible.map(g=>`<button class="inbox-row" data-group="${esc(g.id)}" aria-pressed="${g.id===selected}"><span class="inbox-kicker">${kindName[g.kind]} · ${g.items.length} item${g.items.length===1?'':'s'}</span><b>${esc(g.title)}</b><small>${esc(g.subtitle)}</small></button>`).join('')||'<p class="inbox-note">No matching items.</p>'}</div></aside><div id="detail">${detail(g)}</div></div><p class="inbox-note" style="margin:28px 0">Only approved policies change automatic reconciliation. <a href="demo.html?track=stage">Full demo walkthrough</a> · <a href="index.html">Two-client experiment</a> · <a href="results.html">Results</a></p>${SO.presenting?SO.jev.connection():''}`;
    SO.jev.bind(c(),g,act,render);
    document.getElementById('company').onchange=e=>{clientId=e.target.value;selected='';preview=null;search='';message='';render();};
    document.getElementById('reviewer').onchange=e=>{choices[c().client]=e.target.value;preview=null;render();};
    document.getElementById('refresh').onclick=()=>act(async()=>{preview=null;message='Queue refreshed.';await load();});
    document.getElementById('setup').onclick=()=>{setup=!setup;render();};
    const done=document.getElementById('finish-setup');if(done)done.onclick=()=>{setup=false;message='Workspace reviewed. Select a group to get started.';render();};
    main.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;selected='';preview=null;render();});
    main.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{selected=b.dataset.group;preview=null;render();if(innerWidth<850)document.getElementById('detail').scrollIntoView({behavior:'smooth'});});
    document.getElementById('search').oninput=e=>{const start=e.target.selectionStart;search=e.target.value;render();const input=document.getElementById('search');input.focus();input.setSelectionRange(start,start);};
    const form=document.getElementById('policy-form');if(form)form.onsubmit=e=>{e.preventDefault();act(async()=>{const p=g.policy;const res=await post(p.approve_rule?'/api/playbook/preview-policy':'/api/playbook/preview-band',{client:c().client,track:data.track,period:data.period,rule_id:p.rule_id,condition:p.condition,role:role(),answer:'limit',limit:Number(document.getElementById('limit').value),confirm_rule:p.approve_rule,effective_from:p.approve_rule?data.period+'-01':null});if(res.held)throw Error(res.held);preview={...res,role:role()};drawPreview();});};
    const undo=document.getElementById('undo');if(undo)undo.onclick=()=>{if(!undo.dataset.confirm){undo.dataset.confirm='1';undo.textContent='Confirm: undo latest answer';return;}act(async()=>{const result=await post('/api/retract',{client:c().client,track:data.track,role:role(),correction_id:c().undoable[0].correction_id,note:'Undone from review workspace'});message=`Policy answer undone. ${result.reopened.length} transactions reopened; ${result.resolutions_checked} prior decisions checked.`;await load();});};
  }
  function drawPreview(){const p=preview;document.getElementById('inbox-preview').innerHTML=`<div class="inbox-preview"><div class="inbox-kicker">Preview · nothing saved yet</div><h3>${p.before.needs_review-p.after.needs_review} fewer transactions to review</h3><p>${p.before.needs_review} → ${p.after.needs_review} remain in the company’s queue.</p><div class="inbox-callout"><strong>Policy to approve</strong>${(p.diff.changed||[]).map(change=>`<p>${esc(change.after.text)}</p>${change.after.valid_from?`<span class="inbox-note">Effective ${esc(change.after.valid_from)}</span>`:''}`).join('')}</div><details><summary>Full policy change and audit details</summary>${diffBlock(p.diff,{client:c().client})}</details><table class="inbox-table"><thead><tr><th>Transaction</th><th>Proposed adjustment</th></tr></thead><tbody>${p.changed_items.filter(i=>i.item_kind==='bank').map(i=>`<tr><td>${cite(c().client,i.item_id)}</td><td>${(i.after?.adjustments||[]).map(a=>usd(a.amount)+' to '+esc(a.account)).join(', ')||esc(i.after?.action||'Review')}</td></tr>`).join('')}</tbody></table><div class="inbox-actions"><button class="inbox-btn" id="apply">Approve policy and clear eligible cases</button><button class="inbox-btn secondary" id="cancel-preview">Cancel</button></div><p class="inbox-note">Payment verification holds still apply. You can undo this answer afterward.</p></div>`;document.getElementById('cancel-preview').onclick=()=>{preview=null;document.getElementById('inbox-preview').innerHTML='';};document.getElementById('apply').onclick=()=>act(async()=>{const r=await post('/api/playbook/apply-preview',{preview_id:p.preview_id,role:p.role});if(!r.diff)throw Error(r.held||'No policy change was saved');message=`Policy approved. ${r.reran.length} transactions cleared. Related cases will follow the same rule; verification holds remain.`;preview=null;filter=SO.presenting?'clear':'all';selected='';await load();main.querySelector('.inbox-status').scrollIntoView({behavior:'smooth',block:'center'});});document.getElementById('inbox-preview').scrollIntoView({behavior:'smooth',block:'center'});}
  async function post(path,body){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await res.json();if(!res.ok)throw Error(typeof v.detail==='string'?v.detail:JSON.stringify(v.detail));return v;}
  async function act(fn){if(busy)return;busy=true;main.querySelectorAll('button,select,input,textarea').forEach(x=>x.disabled=true);try{await fn();}catch(e){message=e.message;const s=main.querySelector('.inbox-status');if(s)s.textContent=message;}finally{busy=false;main.querySelectorAll('button,select,input,textarea').forEach(x=>{if(x.getAttribute('aria-label')!=='Adjustment account')x.disabled=false;});}}
  async function load(){const r=await fetch('/api/stage');if(!r.ok)throw Error('The live workspace is temporarily unavailable. Refresh to reconnect, or use the recorded fallback.');data=await r.json();await SO.jev.refresh();for(const x of data.results){if(!choices[x.client])choices[x.client]=x.undoable?.[0]?.by_role||x.role;}if(!clientId)clientId=data.results[0].client;render();}
  main.innerHTML='<div class="panel inbox-empty">Preparing your review queue…</div>';
  try{await load();}catch(e){main.innerHTML=`<div class="panel inbox-empty">${esc(e.message)} <a href="recorded-demo.html">Open recorded fallback</a></div>`;}
})();
