// Jev suggestions stay separate from policy approvals and reconciliation.
(function () {
  const {esc,cite}=SO;
  let status={configured:false}, results={}, notes={};
  const name=r=>(r||'Needs manual triage').replaceAll('_',' ').replace(/\b(ar|ap)\b/gi,x=>x.toUpperCase()).replace(/^./,x=>x.toUpperCase());
  const id=(c,g)=>c.client+':'+g.id;
  const post=async(path,body)=>{const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(typeof data.detail==='string'?data.detail:'Check the Jev request and try again.');return data;};
  SO.jev={
    async refresh(){try{const res=await fetch('/api/jev/status');if(res.ok)status=await res.json();}catch{status={configured:false};}results={};},
    connection(){return `<details class="panel jev-connect"><summary>Jev review assistant · ${status.configured?'Key connected':'Connect Jev'}</summary><p>Jev suggests who should review a case and what information to gather. Only clicking “Get suggestion” sends the selected transactions, company policy, linked evidence and your note to TypeSafe.</p><form id="jev-key-form" class="inbox-actions"><label>TypeSafe API key<input id="jev-key" type="password" autocomplete="off" spellcheck="false" required minlength="20" maxlength="512" placeholder="Paste your API key" aria-label="TypeSafe API key"></label><button class="inbox-btn secondary">${status.configured?'Replace key':'Connect Jev'}</button></form><p class="inbox-note">Saved only in this local server’s ignored workspace, with owner-only file permissions. Never stored in your browser. Connection is verified on your first suggestion. <a href="https://console.typesafe.ai/keys" target="_blank" rel="noopener">Get a TypeSafe key ↗</a></p></details>`;},
    panel(c,g){if(g.kind==='clear')return '';const key=id(c,g);return `<details class="jev-panel" ${SO.presenting ? "" : "open"}><summary>Jev · Find the next step</summary><p class="inbox-note">Get a suggested reviewer and next step from this case’s evidence.</p><label>Additional context <span class="inbox-note">(optional, unverified)</span><textarea id="jev-note" rows="2" maxlength="2000" placeholder="For example: The customer says a remittance breakdown is available.">${esc(notes[key]||'')}</textarea></label><div class="inbox-actions"><button type="button" class="inbox-btn secondary" id="jev-run">${status.configured?'Get suggestion':'Connect Jev to get a suggestion'}</button><span id="jev-progress" class="inbox-note" role="status" aria-live="polite"></span></div><div id="jev-result">${results[key]?this.result(c,results[key]):''}</div></details>`;},
    result(c,r){const role=r.reviewer?name(r.reviewer):'No confident reviewer suggestion';return `<div class="jev-result"><div class="inbox-kicker">${r.cached?'Cached Jev response':'Live Jev response'} · ${r.elapsed_ms} ms${r.cached?' original request':''}</div><h3>${esc(role)}</h3><p>${esc(r.next_step_text)}</p>${r.control_hold?'<p class="inbox-note"><b>Verification hold enforced by Audita.</b> Jev cannot clear it.</p>':''}<p class="inbox-note">Suggested reviewer confidence: ${r.answers.reviewer.confidence.toFixed(2)} / 1. Next-step confidence: ${r.answers.next_step.confidence.toFixed(2)} / 1. These are model confidence scores, not measured accuracy.</p>${r.evidence_ids.length?'<p>Source documents: '+r.evidence_ids.map(x=>cite(c.client,x)).join(' ')+'</p>':''}<details><summary>Model choices and uncertainty</summary>${Object.entries(r.answers).map(([q,a])=>`<p><b>${esc(name(q))}</b>: ${esc(name(a.choice))}</p>${Object.entries(a.probabilities).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="jev-prob"><span>${esc(name(k))}</span><span>${(v*100).toFixed(1)}%</span></div>`).join('')}`).join('')}<p class="inbox-note">Suggestions below ${r.confidence_floor} confidence fall back to manual triage. This is a demo threshold, not a validated performance guarantee.</p></details><p class="inbox-note">Suggestion only. No assignment, policy approval or accounting decision was changed.</p></div>`;},
    bind(c,g,act,render){
      const form=document.getElementById('jev-key-form');
      if(form)form.onsubmit=e=>{e.preventDefault();const input=document.getElementById('jev-key'),key=input.value;input.value='';act(async()=>{await post('/api/jev/key',{key});status={...status,configured:true};render();});};
      if(!g||g.kind==='clear')return;
      const key=id(c,g),note=document.getElementById('jev-note'),btn=document.getElementById('jev-run');
      note.oninput=()=>{notes[key]=note.value;delete results[key];document.getElementById('jev-result').innerHTML='';};
      btn.onclick=()=>{if(!status.configured){const panel=document.querySelector('.jev-connect');panel.open=true;panel.scrollIntoView({behavior:'smooth',block:'center'});document.getElementById('jev-key').focus();return;}
        act(async()=>{document.getElementById('jev-progress').textContent='Jev is reading the case…';try{const r=await post('/api/jev/triage',{client:c.client,item_ids:g.items.map(i=>i.item_id),note:notes[key]||''});results[key]=r;document.getElementById('jev-result').innerHTML=this.result(c,r);}finally{document.getElementById('jev-progress').textContent='';}});};
    }
  };
})();
