(async function(){
  const view=document.getElementById('view'),{esc}=SO;
  try{
    const c=await CO.get('/api/onboarding/company');
    const ready=c.created,learned=c.has_playbook;
    const steps=[['setup.html','1','Your company','Name your reviewers and the accounts you use.',ready],['import.html','2','Historical decisions','Upload bank records, ledger entries and how your team handled them.',learned],['playbook.html','3','Learned policies','Learn patterns from your history and inspect the evidence.',learned],['receipts.html','4','New receipts','Upload later payments with no decisions attached. Let Audita reconcile and escalate exceptions.',false]];
    view.innerHTML=`<section class="panel workspace-hero"><div class="label">${ready?esc(c.name):'Your finance workspace'}</div><h1>${ready?'Your company, your decisions.':'Teach Audita how your company works.'}</h1><p>Learn from the decisions your team already made. Apply that knowledge to new receipts, and review the cases that need a person.</p><div class="actions"><a class="btn btn-primary" href="${!ready?'setup.html':learned?'receipts.html':'import.html'}">${!ready?'Set up my company':learned?'Upload new receipts':'Continue onboarding'}</a>${learned?'<a class="btn btn-secondary" href="reconcile.html">Open review workspace</a>':''}<a class="btn btn-secondary" href="../queue.html?track=stage">Explore sample demo</a></div></section><div class="workspace-cards">${steps.map(([url,n,title,description,done])=>`<a class="panel workspace-card" href="${url}"><span class="label">${done?'Completed':`Step ${n}`}</span><h2>${title}</h2><p>${description}</p><span>Open →</span></a>`).join('')}</div><section class="panel"><div class="panel-body"><h3>Try the full upload flow</h3><p>Use your own CSV exports, or rehearse with a small, labelled synthetic example. The example includes historical decisions and separate undecided receipts.</p><div class="actions"><a class="btn btn-secondary" href="example-csvs.zip" download>Download example CSV pack</a><a class="btn btn-secondary" href="setup.html?example=1">Use example company details</a></div></div></section><section class="panel"><div class="panel-body"><h3>Two separate kinds of data</h3><div class="row2"><div><b>Historical decisions teach the policies</b><p>Past matches, write-offs, adjustments and reviewer decisions, alongside their source records.</p></div><div><b>New receipts test those policies</b><p>Source transactions and supporting records only. Matches and decisions are produced by Audita, with evidence and unresolved questions.</p></div></div><p class="faint">This hackathon workspace accepts CSV exports. All processing stays in the local app, with model requests sent to the configured providers. It does not post to your accounting system.</p></div></section>`;
  }catch(e){view.innerHTML=CO.err(e);}
})();
